/**
 * Shared types for the AI analysis module.
 *
 * The module is split deliberately along one line: **deterministic** analyses
 * (anomaly detection, missing-data detection, carbon cost, scenario/CAPEX
 * arithmetic) run with no API key, are pure functions, and are unit-tested;
 * **generative** analyses (reduction ideas, Q&A, report drafting) call OpenAI and
 * degrade to a documented fallback when `OPENAI_API_KEY` is absent.
 *
 * That split is not an implementation detail — it is the difference between a
 * figure an auditor can reproduce and a suggestion a model made up. Every result
 * type below therefore carries provenance (`source`) so the UI can label it.
 */

/** Where a result came from, so the UI never presents a guess as a calculation. */
export type AnalysisSource =
  /** Computed by deterministic code in this repo. Reproducible. */
  | "deterministic"
  /** Generated by an OpenAI model. Not reproducible; must be labelled. */
  | "llm"
  /** Deterministic fallback used because no API key was configured. */
  | "fallback";

/** Severity shared by every finding type. */
export type Severity = "low" | "medium" | "high";

/**
 * One observation in a monthly emissions series — the input to most analyses.
 *
 * `period` is `YYYY-MM`. `emissions` is tCO2e. `activityData` is optional
 * because intensity checks need it but plain outlier detection does not.
 */
export interface EmissionObservation {
  period: string;
  /** Emission source identifier or message key. */
  sourceKey: string;
  scope: 1 | 2 | 3;
  emissions: number;
  /** Activity data behind the figure, e.g. kWh or litres. */
  activityData?: number;
  activityUnit?: string;
}

/** A single detected issue, whatever the detector. */
export interface Finding {
  /** Stable identifier so the UI can key rows and dedupe across runs. */
  id: string;
  /** Key under the `ai.findings` message namespace. */
  titleKey: string;
  severity: Severity;
  source: AnalysisSource;
  /** The period the finding concerns, when it is period-specific. */
  period: string | null;
  sourceKey: string | null;
  /**
   * Numeric detail for the UI to interpolate into the translated message.
   * Kept as named values rather than a pre-formatted sentence so the finding
   * stays translatable into all four locales.
   */
  detail: Record<string, number | string>;
}

/** Result of a deterministic detector. */
export interface DetectionResult {
  findings: Finding[];
  /** Number of observations examined, for "0 findings in N records" messaging. */
  observationCount: number;
}
